services:
  - type: web
    name: image-studio
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libgl1-mesa-glx
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PORT
        value: "10000"
    plan: free
